## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [1]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [3]:
from sklearn.model_selection import train_test_split
y1 = train_test_split(X[y==1],y[y==1], test_size=10, random_state=42)
y0 = train_test_split(X[y==0],y[y==0], test_size=10, random_state=42)

In [4]:
# y1[3],y0[3]
a = []
for i in range(4):
    a.append(np.concatenate((y1[i],y0[i]),axis=0))
X_train, X_test, y_train, y_test = a

In [5]:
X_test, y_test

(array([[ 95,  96,  97,  98,  99],
        [ 80,  81,  82,  83,  84],
        [ 75,  76,  77,  78,  79],
        [130, 131, 132, 133, 134],
        [ 20,  21,  22,  23,  24],
        [ 60,  61,  62,  63,  64],
        [185, 186, 187, 188, 189],
        [135, 136, 137, 138, 139],
        [195, 196, 197, 198, 199],
        [ 30,  31,  32,  33,  34],
        [725, 726, 727, 728, 729],
        [740, 741, 742, 743, 744],
        [905, 906, 907, 908, 909],
        [475, 476, 477, 478, 479],
        [670, 671, 672, 673, 674],
        [345, 346, 347, 348, 349],
        [705, 706, 707, 708, 709],
        [455, 456, 457, 458, 459],
        [700, 701, 702, 703, 704],
        [910, 911, 912, 913, 914]]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]))